name: Entity-Mechanic
main: com.caved_in.entityspawningmechanic.EntityMechanic
version: 1.0.3
description: A unique entity spawning system, designed for RPG servers!
author: Brandon Curtis (TheGamersCave)
depend: [Commons]
commands:
   newarea:
      usage: /newarea <AreaName> <SpawnRadius>
   areas:
      usage: /areas [list]
   addmob:
      usage: /addmob <AreaName> <MinLevel> <MaxLevel> <MobType> <Boolean[IsElite]> <Percent[Elite Spawn Chance]>